spring:
  application:
    name: MagistralAPI
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_DATABASE_HOST:localhost}
      port: ${REDIS_DATABASE_PORT:6379}
      database: ${REDIS_DATABASE_NAME:0}


idempotency:
  hmac:
    secret-key: ${HMAC_SHA256_V1}

confirmationlink:
  ttl: 86400
  prefix: ${CONFIRMATION_LINK_PREFIX}


mail:
  confirm:
    queue:
      name: ${RABBIT_MQ_QUEUE_CONFIRMATION_NAME:DefaultQueue}

dadata:
  client:
    base-url: https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party
    token: ${DADATA_TOKEN}
    timeout: 30s