spring:
  application:
    name: MagistralAPI
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

idempotency:
  hmac:
    secret-key: ${HMAC_SHA256_V1}