spring:
  application:
    name: MagistralAPI
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]

idempotency:
  hmac:
    secret-key: ${HMAC_SHA256_V1}

dadata:
  client:
    base-url: https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party
    token: ${DADATA_TOKEN}
    timeout: 30s